### ISSUE TITLE
Локализация на английский язык

### ISSUE THREAD

**Issue by nikolai-shabalin** [nikolai-shabalin/grid-overlay#18]
* Для начала понять как это делается у гугла.
* Как он понимает, что сейчас нужно установить английский, а не русский
* в каком/их файлах хранить локализацию
* можно ли сделать язык по умоланию. Например, устновили расширение из германии, то надо подхватить английский, так как немецого не будет

**Comment by nikolai-shabalin** [comment]
Thank you

**Comment by fede91it** [comment]
did it

**Comment by nikolai-shabalin** [comment]
Thank you.
